### PR TITLE
Fix paused flag bugs

### LINKED ISSUE #539: [Bug] KubeCarrier ready, but phase unknown
**Describe the bug**
KubeCarrier object conditions are True, but the phase is `Unkown`

```
apiVersion: operator.kubecarrier.io/v1alpha1
kind: KubeCarrier
metadata:
  creationTimestamp: "2020-08-04T11:51:32Z"
  generation: 1
  name: kubecarrier
  resourceVersion: "2327"
  selfLink: /apis/operator.kubecarrier.io/v1alpha1/kubecarriers/kubecarrier
  uid: 6b6f9929-acdc-4681-8b27-b09740a7d021
spec:
  api:
    authentication:
    - serviceAccount: {}
    - anonymous: {}
status:
  conditions:
  - lastTransitionTime: "2020-08-04T11:51:50Z"
    message: the deployment of KubeCarrier is ready
    reason: DeploymentReady
    status: "True"
    type: DeploymentReady
  - lastTransitionTime: "2020-08-04T11:51:50Z"
    message: the deployment of KubeCarrier and API Server are ready.
    reason: KubeCarrierReady
    status: "True"
    type: Ready
  - lastTransitionTime: "2020-08-04T11:51:46Z"
    message: APIServer is ready
    reason: APIServerReady
    status: "True"
    type: APIServerReady
  observedGeneration: 1
  phase: Unknown
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kubernetes/Openshift Cluster**
- Version

**Desktop (please complete the following information):**

**Additional context**

### LINKED ISSUE #541: [Bug] Always missing PausedCondition if the Paused flag is set before component ready
**Describe the bug**
For example, in KubeCarrier object: https://github.com/kubermatic/kubecarrier/blob/master/pkg/apis/operator/v1alpha1/kubecarrier_types.go#L156-L168
```golang
func (s *KubeCarrier) SetPausedCondition() bool {
	var changed bool
	if !s.IsReady() {
		changed = true
		s.Status.ObservedGeneration = s.Generation
		s.Status.SetCondition(KubeCarrierCondition{
			Type:    KubeCarrierReady,
			Status:  ConditionTrue,
			Reason:  "Paused",
			Message: "Reconcilation is paused, assuming component is ready.",
		})
		return changed
	}
	if !s.IsPaused() {
		changed = true
		s.Status.ObservedGeneration = s.Generation
		s.Status.SetCondition(KubeCarrierCondition{
			Type:    KubeCarrierPaused,
			Status:  ConditionTrue,
			Reason:  "Paused",
			Message: "Reconcilation is paused",
		})
	}
	return changed
}
```
If the `KubeCarrier` is not ready, the controller will only set the condition of `KubeCarrierReady` and return `changed` but it never sets the condition of `KubeCarrierPaused`, which means in this way, the `Phase` will be updated to `Ready` not `Paused`.
This issue also applies to other components. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kubernetes/Openshift Cluster**
- Version

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by jiachengxu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #541 Fixes #539 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix Paused flag bugs.
```

### CODE REVIEW

File: pkg/apis/operator/v1alpha1/catapult_types.go [hunk 1]
```diff
@@ -87,9 +87,9 @@ func (s *CatapultStatus) updatePhase() {
 			s.Phase = CatapultPhasePaused
 			return
 		}
-
+	}
+	for _, condition := range s.Conditions {
```
Comment (aborilov) [inline pkg/apis/operator/v1alpha1/catapult_types.go:91]: why do we need to go twice through `Conditions`?

Comment (jiachengxu) [reply pkg/apis/operator/v1alpha1/catapult_types.go:91]: It was something like:
```golang
func (s *CatapultStatus) updatePhase() {

	for _, condition := range s.Conditions {

		if condition.Type == CatapultPaused && condition.Status == ConditionTrue {
			s.Phase = CatapultPhasePaused
			return
		}

		if condition.Type == CatapultReady {

			switch condition.Status {
			case ConditionTrue:
				s.Phase = CatapultPhaseReady
			case ConditionFalse:
				if condition.Reason == CatapultTerminatingReason {
					s.Phase = CatapultPhaseTerminating
				} else {
					s.Phase = CatapultPhaseNotReady
				}
			case ConditionUnknown:
				s.Phase = CatapultPhaseUnknown
			}
		}
	}
}
```
We need to add `s.Phase = CatapultPhaseUnknown` out of the for loop. Otherwise, if both `Paused` and `Ready` conditions are missing, the `Phase` will not be set. So it becomes:
```golang
func (s *CatapultStatus) updatePhase() {

	for _, condition := range s.Conditions {

		if condition.Type == CatapultPaused && condition.Status == ConditionTrue {
			s.Phase = CatapultPhasePaused
			return
		}

		if condition.Type == CatapultReady {

			switch condition.Status {
			case ConditionTrue:
				s.Phase = CatapultPhaseReady
			case ConditionFalse:
				if condition.Reason == CatapultTerminatingReason {
					s.Phase = CatapultPhaseTerminating
				} else {
					s.Phase = CatapultPhaseNotReady
				}
			case ConditionUnknown:
				s.Phase = CatapultPhaseUnknown
			}
		}
	}
+	s.Phase = CatapultPhaseUnknown
}
```
This cannot work, because it will always set the Phase to `Unknown` if Catapult is `Ready`, so we should return when we set the Phase according to the Ready condition:
```golang
func (s *CatapultStatus) updatePhase() {

	for _, condition := range s.Conditions {

		if condition.Type == CatapultPaused && condition.Status == ConditionTrue {
			s.Phase = CatapultPhasePaused
			return
		}

		if condition.Type == CatapultReady {

			switch condition.Status {
			case ConditionTrue:
				s.Phase = CatapultPhaseReady
			case ConditionFalse:
				if condition.Reason == CatapultTerminatingReason {
					s.Phase = CatapultPhaseTerminating
				} else {
					s.Phase = CatapultPhaseNotReady
				}
			case ConditionUnknown:
				s.Phase = CatapultPhaseUnknown
			}
+                      return
		}
	}
+	s.Phase = CatapultPhaseUnknown
```
This still donsn't work, because when we set the `Paused` condition for an Unready component, we will also set the component to `Ready`, so in the `conditions` slice, if the `Ready` condition comes first, we will set the `Phase` to `Ready` and return, but in this case, the Phase should be `Paused`.

That's the reason that we should first go through the `conditions` to check if the component is `Paused`, then check if it is ready.

Comment (aborilov) [reply pkg/apis/operator/v1alpha1/catapult_types.go:91]: ok, got it.
let's replace the first loop with
```
	if paused, ok := s.GetCondition(KubeCarrierPaused); ok && paused.True() {
		s.Phase = KubeCarrierPhasePaused
		return
	}
```
:) I know that it's also loop through all conditions, but it looks nicer :)

Comment (jiachengxu) [reply pkg/apis/operator/v1alpha1/catapult_types.go:89]: Nice, fixed
